dist: xenial
language: python
python:
    - "3.6.6"
    - "3.7"
cache: pip
install:
    - pip install -r requirements.txt
    - pip install -e .
script:
    - coverage run --source pscheduler_grafana_proxy -m py.test
    - coverage report --fail-under 80
    - flake8 pscheduler_grafana_proxy --statistics
